# Generated by Django 2.0.6 on 2018-10-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('profile_description', models.CharField(max_length=100)),
                ('full_description', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('postal_code', models.CharField(max_length=6)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyAddress', to='agrodata.Company', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/CompanyLogos', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CompanyLogo', to='agrodata.Company', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration', models.CharField(blank=True, max_length=500, null=True)),
                ('usage', models.CharField(blank=True, max_length=500, null=True)),
                ('full_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhysicalProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(blank=True, max_length=500, null=True)),
                ('Colour', models.CharField(blank=True, max_length=500, null=True)),
                ('Taste', models.CharField(blank=True, max_length=500, null=True)),
                ('Flavour', models.CharField(blank=True, max_length=500, null=True)),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductPhysicalProperty', to='agrodata.Ingredients', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/productPictures', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductPicture', to='agrodata.Ingredients', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Ingredients', to='agrodata.IngredientsCategories'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Ingredients', to='agrodata.Company'),
        ),
        migrations.AddField(
            model_name='ingredientdetail',
            name='ingredient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IngredientDetail', to='agrodata.Ingredients', unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='agrodata.Database'),
        ),
    ]
