# Generated by Django 2.0.6 on 2018-10-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
