# Generated by Django 2.0.6 on 2018-08-17 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database_stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='business_stream_id',
        ),
        migrations.DeleteModel(
            name='Business_stream',
        ),
        migrations.AddField(
            model_name='company',
            name='database_stream_id',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='agrodata.Database_stream'),
            preserve_default=False,
        ),
    ]
