# Generated by Django 2.0.6 on 2018-08-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0002_companyaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_description',
            field=models.TextField(null=True),
        ),
    ]
