# Generated by Django 2.0.6 on 2018-08-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0003_company_full_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Ingredients', to='agrodata.IngredientsCategories'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Ingredients', to='agrodata.Company'),
        ),
    ]
