# Generated by Django 2.0.6 on 2018-08-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0003_auto_20180817_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='business_stream_id',
            new_name='business_stream',
        ),
    ]
