# Generated by Django 2.0.6 on 2018-08-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0004_auto_20180817_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='business_stream',
            new_name='business_stream_id',
        ),
    ]
