# Generated by Django 2.0.6 on 2018-09-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0004_auto_20180830_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration', models.CharField(max_length=500)),
                ('usage', models.CharField(max_length=500)),
                ('full_description', models.TextField(null=True)),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='IngredientDetail', to='agrodata.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhysicalProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Colour', models.CharField(max_length=500)),
                ('Taste', models.CharField(max_length=500)),
                ('Flavour', models.CharField(max_length=500)),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductPhysicalProperty', to='agrodata.Ingredients')),
            ],
        ),
    ]
