# Generated by Django 2.0.6 on 2018-10-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0005_auto_20181017_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogo',
            name='picture',
            field=models.ImageField(blank=True, default='/static/imgs/home/avatar.png', null=True, upload_to='uploads/CompanyLogos', verbose_name='Image'),
        ),
    ]
