# Generated by Django 2.0.6 on 2018-09-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0005_ingredientdetail_productphysicalproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/productPictures', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProductPicture', to='agrodata.Ingredients')),
            ],
        ),
        migrations.AddField(
            model_name='productphysicalproperty',
            name='appearance',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
