# Generated by Django 2.0.6 on 2018-09-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrodata', '0006_auto_20180906_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='uploads/CompanyLogos', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CompanyLogo', to='agrodata.Company')),
            ],
        ),
    ]
